format = """
$status \
$time \
$username\
$hostname\
$shlvl\
$kubernetes\
$directory\
$git_branch\
$git_commit\
$git_state\
$git_status\
$docker_context\
$package\
$cmake\
$nodejs\
$perl\
$python \
$ruby\
$rust\
$terraform\
$vagrant\
$nix_shell\
$conda\
$aws \
$env_var\
$cmd_duration\
$line_break\
$character"""

# Don't print a new line at the start of the prompt
# add_newline = false

[aws]
format = '\[AWS: [$profile/($region)]($style)\]'
style = 'white'

[character]
success_symbol = " [➜](green)"
error_symbol = " [x](bold red)"

[cmd_duration]
min_time = 1000

[directory]
truncation_length = 100
truncate_to_repo = true
style = " yellow"
format = "[:$path]($style)[$read_only]($read_only_style) "

[git_branch]
style = "white"
format = '[\($symbol$branch\)]($style) '

[git_status]
style="red"
format = '([\[$conflicted$deleted$renamed$modified$staged$behind$untracked\]]($style) )'
modified = '*'

[python]
style="yellow"
format = '[\[${symbol}${pyenv_prefix}(${version})(\($virtualenv\))\]]($style)'

[status]
disabled = false
format = '[\[$status - $common_meaning\]](green)'

[time]
disabled = false
format = '[\[$time\]](green) '
#time_format = "%a %b %d %Y %l:%M%p (GMT%z)"
time_format = "%a %b %d %Y %l:%M%p (GMT%z)"

[env_var]
variable = "0"


#### Disabled modules ####

# add these back to format if you want them:
# $hg_branch\
# $dart\
# $dotnet\
# $elixir\
# $elm\
# $erlang\
# $golang\
# $helm\
# $java\
# $julia\
# $kotlin\
# $nim\
# $ocaml\
# $php\
# $purescript\
# $swift\
# $zig\
# $memory_usage\
# $gcloud\
# $openstack\
# $crystal\
# $lua\
# $jobs\
# $battery\
[hg_branch]
disabled = true
[dart]
disabled = true
[dotnet]
disabled = true
[elixir]
disabled = true
[elm]
disabled = true
[erlang]
disabled = true
[golang]
disabled = true
[helm]
disabled = true
[java]
disabled = true
[julia]
disabled = true
[kotlin]
disabled = true
[nim]
disabled = true
[ocaml]
disabled = true
[php]
disabled = true
[purescript]
disabled = true
[swift]
disabled = true
[zig]
disabled = true
[memory_usage]
disabled = true
[gcloud]
disabled = true
[openstack]
disabled = true
[crystal]
disabled = true
[lua]
disabled = true
[jobs]
disabled = true
[battery]
disabled = true
[package]
disabled = true
